[project]
name = "cyfi"
version = "1.1.5"
authors = [
  {name = "DrivenData", email = "info@drivendata.org"}
]
description = "Estimate cyanobacteria density in small, inland water bodies using Sentinel-2 satellite imagery."
readme = "README.md"
license = { file = "LICENSE" }
keywords = [
  "cyanobacteria",
  "harmful algal blooms",
  "HABs",
  "sentinel-2",
  "satellite imagery",
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
requires-python = ">=3.10"
dependencies = [
  "cloudpathlib[s3]>=0.4.1",
  "geopandas",
  "geopy",
  "GitPython",
  "gradio>=5.0",
  "lightgbm",
  "loguru",
  "matplotlib",
  "numpy",
  "odc-stac",
  "opencv-python",
  "pandas",
  "planetary-computer",
  "platformdirs",
  "plotly",
  "pydantic>=2.0",
  "pystac",
  "pystac-client",
  "scikit-learn>=1.4",
  "seaborn",
  "repro-zipfile",
  "rioxarray",
  "tqdm",
  "typer>=0.16.0",
  "xarray[accel,io,parallel]",
]

[dependency-groups]
dev = [
  "build",
  "jupyter",
  "mkdocs",
  "mkdocs-bootswatch",
  "pytest",
  "pytest-cov",
  "pytest_mock",
  "ruff>=0.15.12",
]

[project.scripts]
cyfi = "cyfi.cli:app"

[project.urls]
"Repository" = "https://github.com/drivendataorg/cyfi"
"Documentation" = "https://cyfi.drivendata.org/"
"Bug Tracker" = "https://github.com/drivendataorg/cyfi/issues"
"Changelog" = "https://cyfi.drivendata.org/changelog/"

[build-system]
requires = ["uv_build >= 0.11.7, <0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""

[tool.ruff]
line-length = 99
src = ["cyfi", "tests", "docs"]
target-version = "py310"

[tool.ruff.lint.isort]
known-first-party = ["cyfi"]
force-sort-within-sections = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov=cyfi --cov-report=term --cov-report=html --cov-report=xml"
testpaths = ["tests"]

[tool.coverage.run]
source = ["cyfi"]
