site_name: cyfi
site_url: https://cyfi.drivendata.org/
site_description: A python package to predict cyanobacteria density based on Sentinel-2 satellite imagery
repo_url: https://github.com/drivendataorg/cyfi
edit_uri: ""
theme:
  name: flatly

nav:
  - Installation: "installation.md"
  - Quickstart: "index.md/#quickstart"
  - Visualize: "explorer.md"
  - Background: "about.md"
  - Changelog: "changelog.md"

markdown_extensions:
  - toc:
      permalink: True
      toc_depth: 3

extra_css:
  - style.css

plugins:
  - search

watch:
  - ../cyfi