name: release

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build and publish new release
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: "3.10"

      - name: Build package
        id: build_package
        run: |
          VERSION="$(uv run -m vspect read .)"
          echo "Building version ${VERSION}"
          echo "version=${VERSION}" >> "${GITHUB_OUTPUT}"
          make dist

      - name: Build docs
        run: |
          make docs

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.14.0
        with:
          user: ${{ secrets.PYPI_TEST_USERNAME }}
          password: ${{ secrets.PYPI_TEST_PASSWORD }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true

      - name: Publish to Production PyPI
        uses: pypa/gh-action-pypi-publish@v1.14.0
        with:
          user: ${{ secrets.PYPI_PROD_USERNAME }}
          password: ${{ secrets.PYPI_PROD_PASSWORD }}
          skip_existing: false
