name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
  schedule:
    # Run every Sunday
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: "3.10"
          enable-cache: true

      - name: Lint package
        run: |
          make lint

  tests:
    name: Test suite (${{ matrix.os }}, Python ${{ matrix.python-version }})
    needs: code-quality
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", 3.11]
    env:
      TERM: dumb
      MPLBACKEND: Agg

    steps:
      - uses: actions/checkout@v6

      - name: Set up uv with Python ${{ matrix.python-version }}

        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install OpenMP with Homebrew
        if: ${{ runner.os == 'macOS' && runner.arch == 'ARM64' }}
        run: |
          brew install libomp

      - name: Run tests
        run: |
          uv run --isolated --no-editable --upgrade make test

      - name: Upload coverage to codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true

  docs:
    name: Docs
    needs: code-quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: "3.10"
          enable-cache: true

      - name: Test Building Docs
        run: |
          make docs

  notify:
    name: Notify failed build
    needs: [code-quality, tests, docs]
    if: failure() && github.event.pull_request == null
    runs-on: ubuntu-latest
    steps:
      - uses: jayqi/failed-build-issue-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
