name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Lint package
        run: |
          make lint

  tests:
    name: Test suite (${{ matrix.os }}, Python ${{ matrix.python-version }})
    needs: code-quality
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", 3.11]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10 with Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          channels: conda-forge

      - name: Install dependencies
        run: |
          which python
          conda update pip
          conda install -c conda-forge lightgbm
          conda install -c conda-forge xarray dask netCDF4 bottleneck
          pip install -e .[dev]

      - name: Run tests
        run: |
          make test

      # - name: Upload coverage to codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ./coverage.xml
      #     fail_ci_if_error: true
      #   if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Build distribution and test installation
        shell: bash
        run: |
          make dist
          python -m pip install dist/cyfi-*.whl --no-deps --force-reinstall
          cyfi --version
          python -m pip install dist/cyfi-*.tar.gz --no-deps --force-reinstall
          cyfi --version
